import { Resend } from 'resend';
import dotenv from 'dotenv';
dotenv.config();

const resend = new Resend(process.env.RESEND_API_KEY);

interface SendAuditEmailParams {
  email: string;
  companyName?: string;
  totalMonthlySavings: number;
  totalAnnualSavings: number;
  isHighSavings: boolean;
}

export const sendAuditEmail = async (params: SendAuditEmailParams): Promise<void> => {
  const { email, companyName, totalMonthlySavings, totalAnnualSavings, isHighSavings } = params;

  const greeting = companyName ? `Hi ${companyName} team,` : 'Hi there,';

  const highSavingsBlock = isHighSavings
    ? `
    <div style="background:#059669;padding:20px;border-radius:8px;margin:20px 0;">
      <p style="color:white;margin:0;font-weight:bold;">🎯 You qualify for a Credex consultation</p>
      <p style="color:#d1fae5;margin:8px 0 0;">With $${totalMonthlySavings}/mo in potential savings, our team can help you capture even more through discounted AI credits.</p>
      <a href="https://credex.rocks" style="display:inline-block;margin-top:12px;background:white;color:#059669;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:bold;">Book Free Consultation →</a>
    </div>
    `
    : '';

  try {
    await resend.emails.send({
      from: 'SpendSmart AI <onboarding@resend.dev>',
      to: email,
      subject: `Your AI Spend Audit — $${totalMonthlySavings}/mo savings found`,
      html: `
        <div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:20px;background:#0f172a;color:#e2e8f0;">
          <h1 style="color:#34d399;font-size:24px;">SpendSmart AI Audit Report</h1>
          
          <p>${greeting}</p>
          <p>Your AI spend audit is complete. Here's your summary:</p>

          <div style="background:#1e293b;border:1px solid #334155;border-radius:8px;padding:24px;text-align:center;margin:20px 0;">
            <p style="color:#94a3b8;margin:0 0 8px;">Potential Monthly Savings</p>
            <p style="color:#34d399;font-size:48px;font-weight:bold;margin:0;">$${totalMonthlySavings.toLocaleString()}</p>
            <p style="color:#64748b;margin:8px 0 0;">$${totalAnnualSavings.toLocaleString()} per year</p>
          </div>

          ${highSavingsBlock}

          <p style="color:#94a3b8;font-size:14px;margin-top:32px;">
            This audit was generated by SpendSmart AI — a free tool by Credex.<br/>
            <a href="https://credex.rocks" style="color:#34d399;">credex.rocks</a>
          </p>
        </div>
      `,
    });
  } catch (error) {
    console.error('Email send error:', error);
    // Email failure should not break the app
  }
};